=== RajarshiBarman/2247229_XML/dom.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="codemia">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="users" minOccurs="1" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="id" type="xs:string"></xs:element>
                            <xs:element name="fname" type="xs:string"></xs:element>
                            <xs:element name="lname" type="xs:string"></xs:element>
                            <xs:element name="user_id">
                                <xs:simpleType>
                                    <xs:restriction base="xs:integer">
                                        <xs:pattern value="[0-9]{3}"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="dob" type="xs:date"></xs:element>
                            <xs:element name="age" type="xs:integer"></xs:element>
                            <xs:element name="phno">
                                <xs:simpleType>
                                    <xs:restriction base="xs:integer">
                                        <xs:pattern value="[0-9]{10}"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="email_id" type="xs:string"></xs:element>
                            <xs:element name="uname" type="xs:string"></xs:element>
                        </xs:sequence> 
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== RajarshiBarman/2247229_XML/dom.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet href="dom.xsl" type="text/xsl"?>
<codemia xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="dom.xsd">
    <users>
        <id>1</id>
        <fname>Rajarshi</fname>
        <lname>Barman</lname>
        <user_id>121</user_id>
        <dob>2001-05-07</dob>
        <age>21</age>
        <phno>8617582806</phno>
        <email_id>raj@gmail.com</email_id>
        <uname>Zeus</uname>
    </users>
    <users>
        <id>2</id>
        <fname>Isar</fname>
        <lname>Rahman</lname>
        <user_id>122</user_id>
        <dob>2000-12-28</dob>
        <age>22</age>
        <phno>7784521958</phno>
        <email_id>isa@gmail.com</email_id>
        <uname>Cigg</uname>
    </users>
</codemia>
